<a href="https://colab.research.google.com/github/OleksiiLozovyi/goit-algo-hw-03/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from numpy import random


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, -8, 9, -11])
print(a)

[  1   2   3   4   5   6   7  -8   9 -11]


In [ ]:
b = np.zeros((3, 3), dtype=int)
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
d = np.random.randint(1, 100, (5, 5))
print(d)

[[ 4  9 70 16 82]
 [78 78 28 33 31]
 [63 36 14 14 34]
 [55 60 66 68  5]
 [93 31 90 50 33]]


In [ ]:
e = np.random.randint(0, 2, (4, 4))
print(e)

[[0 1 1 0]
 [0 0 1 1]
 [1 0 0 1]
 [1 1 0 0]]


In [ ]:
f = np.array([1, 2, 3, 4, 5])
g = np.array([4, 6, 8, 9, 1])
print(f+g)
print(f-g)
print(f*g)

[ 5  8 11 13  6]
[-3 -4 -5 -5  4]
[ 4 12 24 36  5]


In [ ]:
h = np.array([2, 7, 4, 2, 1, 6, 5])
i = np.array([3, 5, 6, 8, 1, 5, 7])
print(np.dot(h, i))

147


In [ ]:
j = np.array([[2, 7], [3, 6]])
k = np.array([[4, 5], [1, 9], [8, 3]])
print(np.dot(j, k))

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [ ]:
l = np.array([[2, 4, 5], [7, 1, 9], [9, 8, 3]])
print(np.linalg.inv(l))

[[-0.20474777  0.08308605  0.09198813]
 [ 0.17804154 -0.115727    0.0504451 ]
 [ 0.13946588  0.05934718 -0.07715134]]


In [ ]:
m = np.array([[2, 4, 5, 1], [7, 1, 9, 3], [9, 8, 3, 4], [3, 4, 5, 1]])
print(m.T)

[[2 7 9 3]
 [4 1 8 4]
 [5 9 3 5]
 [1 3 4 1]]


In [ ]:
n = np.array([[2, 4, 5], [7, 1, 9], [9, 8, 3], [3, 4, 5]])
o = np.array([2, 4, 6, 8])
print(np.dot(n, o))

ValueError: shapes (4,3) and (4,) not aligned: 3 (dim 1) != 4 (dim 0)

In [ ]:
n = np.array([[0, 1], [0, 0], [0, 1]])
o = np.array([1, 1, 0])
print(np.dot(n, o))

ValueError: shapes (3,2) and (3,) not aligned: 2 (dim 1) != 3 (dim 0)

In [ ]:
p = np.array([[8, 1], [2, 3]])
r = np.array([[1, 3], [4, 5]])
print(p*r)
print(np.dot(p, r))

[[ 8  3]
 [ 8 15]]
[[12 29]
 [14 21]]


In [ ]:
s = np.array([[81, 21, 53, 75, 6], [7, 14, 58, 22, 13], [41, 53, 68, 91, 10], [6, 7, 9, 1, 4], [31, 3, 16, 1, 21]])
print(s.sum())

712


In [ ]:
t = np.array([[1, 3, 4, 3], [6, 2, 3, 5], [1, 1, 6, 3], [4, 5, 6, 2]])
u = np.array([[1, 8, 4, 3], [6, 1, 3, 5], [2, 1, 6, 5], [4, 5, 6, 8]])
print(t-u)

[[ 0 -5  0  0]
 [ 0  1  0  0]
 [-1  0  0 -2]
 [ 0  0  0 -6]]


In [ ]:
v = np.array([[1, 0, 1], [1, 1, 1], [1, 1, 0]])
print(sum(v[0: 3]))


[3 2 2]


In [ ]:
x = ([18, 3, 41, 95])
print(np.sqrt(x[0: 5]))

[4.24264069 1.73205081 6.40312424 9.74679434]
